### ISSUE TITLE
class实例情况下，方法用简写方式的话好像就拷贝不到了。

### ISSUE THREAD

**Issue by hecheng1996lzg** [w995928555/d-copy#1]
class a{f(){console.log(1)}};
let a1 = new a();
let a2 = deepCopy(a1);    // a2没有拷贝到f()方法

class b{f = function(){console.log(1)}};
let b1 = new b();
let b2 = deepCopy(b1);    // 不使用简写，能够拷贝到...

**Comment by w995928555** [comment]
简写方式是挂载到原型链上面的，而不是当前实例上面。非简写方式是挂载到当前实例上面，所以能copy到。
